import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import Provider from "./Provider";
import { ColorSchemeScript } from "@mantine/core";
import '@mantine/core/styles.css';

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Desafio Front-End",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        />
        <ColorSchemeScript />
      </head>
      <body className={outfit.className}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
